package com.snapsearch.data

import android.content.Context
import io.objectbox.Box
import io.objectbox.BoxStore

/**
 * Process-wide ObjectBox store singleton, replacing the earlier Room `SnapSearchDatabase`.
 *
 * `MyObjectBox` is generated by the ObjectBox Gradle plugin at build time from the `@Entity`
 * classes in this module, in this same package (`com.snapsearch.data`) — it mirrors how Room
 * generated its database implementation, and won't resolve until the project has been built
 * at least once with the `io.objectbox` plugin applied.
 */
object ObjectBoxStore {
    @Volatile
    private var store: BoxStore? = null

    fun get(context: Context): BoxStore {
        return store ?: synchronized(this) {
            store ?: MyObjectBox.builder()
                .androidContext(context.applicationContext)
                .build()
                .also { store = it }
        }
    }

    fun imageBox(context: Context): Box<ImageEntity> = get(context).boxFor(ImageEntity::class.java)
}
